In [1]:
import numpy as np

In [2]:
input = np.array([ 0.05, .1])
y = np.array([.01, .99])
w1 = np.array([[.15, .2],[.25, .3]])
w2 = np.array([[.4, .45],[.5, .55]])
b1 = np.array([.35, .35])
b2 = np.array([.6, .6])

print input.shape
print w1.shape
print w2.shape
print b1
print b2

(2,)
(2, 2)
(2, 2)
[ 0.35  0.35]
[ 0.6  0.6]


In [3]:
neth1 = input.dot(w1.T) + b1
oh1 = 1 / (1 + np.exp(-neth1))

print neth1
print oh1

[ 0.3775  0.3925]
[ 0.59326999  0.59688438]


In [4]:
neto1 = oh1.dot(w2.T) + b2
oo1 = 1 / (1 + np.exp(-neto1))

print neto1
print oo1

[ 1.10590597  1.2249214 ]
[ 0.75136507  0.77292847]


In [5]:
diff = y - oo1
e = np.square(diff) / 2
etot = np.sum(e)

print diff
print e
print etot

[-0.74136507  0.21707153]
[ 0.27481108  0.02356003]
0.29837110876


In [6]:
de = (-diff)[np.newaxis]
doo1 = (oo1 * (1 - oo1))[np.newaxis]
de_dneto1 = de.T * np.repeat(doo1.T,2,axis=1)
dneto1 = oh1
dw2 = de_dneto1 * dneto1

print de
print doo1
print de_dneto1
print dneto1
print dw2

[[ 0.74136507 -0.21707153]]
[[ 0.1868156   0.17551005]]
[[ 0.13849856  0.13849856]
 [-0.03809824 -0.03809824]]
[ 0.59326999  0.59688438]
[[ 0.08216704  0.08266763]
 [-0.02260254 -0.02274024]]


In [7]:
de_doh = de_dneto1 * w2 # effects of oh
detot_doh = np.sum(de_doh, axis=0) # total effect of oh per h
dh_dnet = (dneto1 * (1 - dneto1))[np.newaxis]
de_dneth = detot_doh.T * np.repeat(dh_dnet.T, 2, axis=1)
dneth_dw1 = input
detot_dw1 = de_dneth * dneth_dw1

print de_doh
print detot_doh
print dh_dnet
print de_dneth
print dneth_dw1
print detot_dw1
print w1 - (0.5*detot_dw1)

[[ 0.05539942  0.06232435]
 [-0.01904912 -0.02095403]]
[ 0.03635031  0.04137032]
[[ 0.24130071  0.24061342]]
[[ 0.00877135  0.00998269]
 [ 0.00874637  0.00995425]]
[ 0.05  0.1 ]
[[ 0.00043857  0.00099827]
 [ 0.00043732  0.00099543]]
[[ 0.14978072  0.19950087]
 [ 0.24978134  0.29950229]]


In [8]:
def forward_prop(input, w1, b1, w2, b2):
    neth1 = input.dot(w1.T) + b1
    oh1 = 1 / (1 + np.exp(-neth1))
    
    neto1 = oh1.dot(w2.T) + b2
    oo1 = 1 / (1 + np.exp(-neto1))

    return oo1

def print_loss(y, out):
    diff = y - oo1
    e = np.square(diff) / 2
    etot = np.sum(e)
    
    print etot

def backprop(out, y, w1, b1, w2, b2):
    diff = y - out
    de = (-diff)[np.newaxis]
    doo1 = (out * (1 - out))[np.newaxis]
    de_dneto1 = de.T * np.repeat(doo1.T,2,axis=1)
    dneto1 = oh1
    dw2 = de_dneto1 * dneto1
    
    de_doh = de_dneto1 * w2 # effects of oh
    detot_doh = np.sum(de_doh, axis=0) # total effect of oh per h
    dh_dnet = (dneto1 * (1 - dneto1))[np.newaxis]
    de_dneth = detot_doh.T * np.repeat(dh_dnet.T, 2, axis=1)
    dneth_dw1 = input
    dw1 = de_dneth * dneth_dw1
    return dw1, dw2

def backprop_bias(out, y, w1, b1, w2, b2):
    diff = y - out
    de = (-diff)[np.newaxis]
    doo1 = (out * (1 - out))[np.newaxis]
    de_dneto1 = de.T * np.repeat(doo1.T,2,axis=1)
    dneto1 = oh1
    dw2 = de_dneto1 * dneto1
    
    
    
    de_doh = de_dneto1 * w2 # effects of oh
    detot_doh = np.sum(de_doh, axis=0) # total effect of oh per h
    dh_dnet = (dneto1 * (1 - dneto1))[np.newaxis]
    de_dneth = detot_doh.T * np.repeat(dh_dnet.T, 2, axis=1)
    dneth_dw1 = input
    dw1 = de_dneth * dneth_dw1
    return dw1, dw2

iteration = 10
learn_rate = 0.5
input = np.array([ 0.05, .1])
y = np.array([.01, .99])
w1 = np.array([[.15, .2],[.25, .3]])
w2 = np.array([[.4, .45],[.5, .55]])
b1 = np.array([.35, .35])
b2 = np.array([.6, .6])
modu = iteration / 10
print "iteration of", modu
for i in range(iteration):
    oo1 = forward_prop(input, w1, b1, w2, b2)
    if i % modu == 0: print_loss(y, oo1); print oo1
    grads_w1, grads_w2 = backprop(oo1, y, w1, b1, w2, b2)
    w1 = w1 - (learn_rate * grads_w1)
    w2 = w2 - (learn_rate * grads_w2)

oo1 = forward_prop(input, w1, b1, w2, b2)
print oo1

iteration of 1
0.29837110876
[ 0.75136507  0.77292847]
0.291027741322
[ 0.74208804  0.77528487]
0.283546901012
[ 0.73247651  0.77758179]
0.275942706531
[ 0.72253799  0.77982144]
0.268231699643
[ 0.71228333  0.78200596]
0.260432749382
[ 0.70172688  0.78413738]
0.252566878376
[ 0.69088656  0.78621763]
0.244657008763
[ 0.67978383  0.78824856]
0.236727629819
[ 0.6684436   0.79023194]
0.228804394575
[ 0.65689401  0.79216944]
[ 0.64516603  0.79406268]


In [16]:
import matplotlib.pyplot as plt
%matplotlib inline

for i in range(10):
    for j in range(10):
        scale = 0.1
        print i*scale,j*scale,forward_prop(np.array([i*scale,j*scale]), w1,b1,w2,b2)
    print

0.0 0.0 [ 0.64515362  0.7923108 ]
0.0 0.1 [ 0.64516158  0.79356219]
0.0 0.2 [ 0.64516943  0.79480198]
0.0 0.3 [ 0.64517718  0.79602988]
0.0 0.4 [ 0.64518481  0.7972456 ]
0.0 0.5 [ 0.64519231  0.79844888]
0.0 0.6 [ 0.64519968  0.79963945]
0.0 0.7 [ 0.64520691  0.80081709]
0.0 0.8 [ 0.64521399  0.80198156]
0.0 0.9 [ 0.64522091  0.80313268]

0.1 0.0 [ 0.6451626   0.79331923]
0.1 0.1 [ 0.64517046  0.79456126]
0.1 0.2 [ 0.64517822  0.79579144]
0.1 0.3 [ 0.64518586  0.7970095 ]
0.1 0.4 [ 0.64519337  0.79821516]
0.1 0.5 [ 0.64520076  0.79940816]
0.1 0.6 [ 0.645208    0.80058827]
0.1 0.7 [ 0.64521509  0.80175525]
0.1 0.8 [ 0.64522202  0.8029089 ]
0.1 0.9 [ 0.64522879  0.80404903]

0.2 0.0 [ 0.64517149  0.7943201 ]
0.2 0.1 [ 0.64517926  0.79555256]
0.2 0.2 [ 0.64518691  0.79677294]
0.2 0.3 [ 0.64519443  0.79798098]
0.2 0.4 [ 0.64520183  0.7991764 ]
0.2 0.5 [ 0.64520908  0.80035896]
0.2 0.6 [ 0.64521619  0.80152845]
0.2 0.7 [ 0.64522314  0.80268464]
0.2 0.8 [ 0.64522992  0.80382734]
0.2 0.9 [ 0.